// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_void = "CgkIgqT3zdweEAIQCA"; // <GPGSID>
        public const string achievement_freezing = "CgkIgqT3zdweEAIQBw"; // <GPGSID>
        public const string achievement_peace = "CgkIgqT3zdweEAIQBQ"; // <GPGSID>
        public const string achievement_traveller = "CgkIgqT3zdweEAIQCQ"; // <GPGSID>
        public const string achievement_pro = "CgkIgqT3zdweEAIQDQ"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIgqT3zdweEAIQEA"; // <GPGSID>
        public const string achievement_rookie = "CgkIgqT3zdweEAIQDA"; // <GPGSID>
        public const string achievement_money_craze = "CgkIgqT3zdweEAIQAQ"; // <GPGSID>
        public const string achievement_ninja = "CgkIgqT3zdweEAIQDg"; // <GPGSID>
        public const string achievement_warmth = "CgkIgqT3zdweEAIQBg"; // <GPGSID>
        public const string achievement_loaded = "CgkIgqT3zdweEAIQBA"; // <GPGSID>
        public const string achievement_money_monster = "CgkIgqT3zdweEAIQAg"; // <GPGSID>
        public const string achievement_unstoppable = "CgkIgqT3zdweEAIQCg"; // <GPGSID>
        public const string achievement_godly = "CgkIgqT3zdweEAIQCw"; // <GPGSID>
        public const string achievement_maniac = "CgkIgqT3zdweEAIQDw"; // <GPGSID>
        public const string achievement_money_maniac = "CgkIgqT3zdweEAIQAw"; // <GPGSID>

}

